server:
  port: 8010
spring:
  application:
    name: ConsumerUser
eureka:
  client:
    serverUrl:
      defaultZone: http://129.204.68.55:8761/eureka/
  instance:
    prefer-ip-address: true